#! /bin/bash
# getfromsolr.sh
# Diagnostic program to display marc records.
# $Id: getfromsolr.sh 

E_BADARGS=65

scriptdir=$( (cd -P $(dirname $0) && pwd) )

if [[ "$SOLRMARC_MEM_ARGS" == "" ]] 
then
    SOLRMARC_MEM_ARGS='@MEM_ARGS@'
fi

SOLRWAR_OR_JARS=@SOLR_JAR_DEF@

java $SOLRMARC_MEM_ARGS $SOLRWAR_OR_JARS -Done-jar.main.class="org.solrmarc.marc.SolrReIndexer" -jar $scriptdir/@CUSTOM_JAR_NAME@ $1 $2 $3 2> /dev/null

exit 0

