#! /bin/bash
# marcsorter.sh
# Program to sort marc records numerically based on 001 field
# $Id: marcsorter.sh 

E_BADARGS=65

scriptdir=$( (cd -P $(dirname $0) && pwd) )

if ! [ -p /dev/stdin ]
then  
  if [ $# -eq 0 ]
  then
    echo "    Usage: `basename $0` ./path/to/marc.mrc > sorted_output_file.mrc"
    exit $E_BADARGS
  fi
  arg1=$1
  arg2=$2
else
  arg1=$1
  arg2=-
fi

java -Done-jar.main.class="org.solrmarc.marc.MarcSorter" -jar $scriptdir/@CUSTOM_JAR_NAME@ $arg1 $arg2

exit 0

