#! /bin/bash

E_BADARGS=65
scriptdir=$( (cd -P $(dirname $0) && pwd) )

case $1 in
*\.jar) jar=$1 ;;
*config.properties) config=$1
esac

case $2 in
*\.jar) jar=$2 ;;
*config.properties) config=$2
esac

if [[ "$jar" = "" ]] 
then
    jar="$scriptdir/@CUSTOM_JAR_NAME@"
fi

java -Done-jar.main.class="org.solrmarc.tools.PropertyFileFetcher" -jar $jar $config

