#!/bin/bash

scriptdir=$( (cd -P $(dirname $0) && pwd) )
if ! [ -e $scriptdir/SolrMarc.jar ] 
then
  scriptdir=$( (cd -P $(dirname $0)/.. && pwd) )
fi

location_file=/lib_content27/marc/incoming/location.txt

out_dir=/lib_content27/marc/full_dump_patched
tmp_out_dir=/lib_content27/marc/full_dump_patched_tmp
patch_dir=/lib_content27/marc/patched

mkdir $tmp_out_dir 2> /dev/null

for file in `find $out_dir -name '*.mrc' -print | sort`
do 
    echo $file
    fname=`basename $file`
    froot=`basename $file .mrc`
    dir=`dirname $file`
    java -Dsolrmarc.main.class="org.solrmarc.marc.MarcPatcher" -jar $scriptdir/SolrMarc.jar $file  $location_file handleAllLocs $patch_dir/${froot}_patched.mrc $tmp_out_dir/$fname 
done
