#!/bin/bash

endId=u0
PATH=/usr/local/projects/solrmarc-2.0/dist:$PATH

for file in /usr/local/projects/marc/full_dump_updated/*.mrc 
do
    startId=$endId
    file1=`echo $file | sed -e 's/\([^0-9]*\)[0-9]*.*/\1/'`
    file2=`echo $file | sed -e 's/[^0-9]*0*\([1-9][0-9]*\).*/\1/'`
    file3=`echo $file | sed -e 's/[^0-9]*[0-9]*\(.*\)/\1/'`
    file2=`echo $((file2+1001)) | sed -e 's/.\(...\)/\1/'`
    nextfile=$file1$file2$file3
    len=`head -c 5 $nextfile 2> /dev/null`
    if [ $? != 0 ] 
        then
            endId=u9999999999
        else
            endId=`head -c $len $nextfile | printrecord '001'| sed -e 's/001 //'`
    fi
    echo $file  $startId  $endId
    marcupdate -min $startId -max $endId $file $1 > $file.updated
    mv $file.updated $file
done
