#! /bin/bash
# optimizesolr
# Run an optimize process on the solr index
# $Id: optimizesolr

E_BADARGS=65

scriptdir=$( (cd -P $(dirname $0) && pwd) )

if ! [ -p /dev/stdin ]
then  
  if [ $# -eq 0 ]
  then
    echo "    Usage: `basename $0` [config.properties] "
    echo "      Note that if the config.properties file is not specified the Jarfile will be searched for"
    echo "      a file whose name ends with \"config.properties\""
    exit $E_BADARGS
  fi
fi

java @MEM_ARGS@ -Dmarc.source="NONE" -Dmarc.optimize_at_end="true" -jar $scriptdir/@CUSTOM_JAR_NAME@ $1 

exit 0

