#! /bin/bash
# getfromsolr.sh
# extracts complete MARC records from Solr index documents.
# $Id: getfromsolr.sh 

E_BADARGS=65

scriptdir=$( (cd -P $(dirname $0) && pwd) )
if ! [ -e $scriptdir/SolrMarc.jar ] 
then
  scriptdir=$( (cd -P $(dirname $0)/.. && pwd) )
fi

if [ $# -eq 0 ]
  then
    echo "    Usage: `basename $0` http://remoteMachine:port/solr id:u30980"
    echo "    Usage: `basename $0` id:u38989"
    exit $E_BADARGS
fi

id=
url=
config=
flag=
field=

handle_arg() {
  if [ ! -z $1 ]
  then
    case $1 in
      http*) url=$1 ;;
      *.properties) config=$1 ;;
      *:*) query=$1 ;;
      [A-Za-z0-9]*)
         if [[ "$id" == ""  && "$query" == "" ]]
         then
            id=$1
         else
            field=$1
         fi
         ;;
      -v) flag=$1 ;;
     -vv) flag=$1 ;;
     esac
   fi
}

handle_arg $1
handle_arg $2
handle_arg $3
handle_arg $4
handle_arg $5

if [[ "$query" == "" && "$id" != "" ]]
then
    query="id:$id"
fi

if [[ "$flag" == "-vv" ]] 
then
  echo config = $config
  echo url = $url
  echo query = $query
  echo id = $id
  echo field = $field
fi

if [ "$url" == "" ]
then
    java -Dsolrmarc.main.class="org.solrmarc.marc.SolrReIndexer" -jar $scriptdir/SolrMarc.jar $config "$query" $field 2> /dev/null
else
    java -Dsolrmarc.main.class="org.solrmarc.solr.RemoteSolrSearcher" -jar $scriptdir/SolrMarc.jar $flag $url "$query" $field 
fi

exit 0

