#! /bin/bash

E_BADARGS=65
scriptdir=$( (cd -P $(dirname $0) && pwd) )

case $1 in
*\.jar) jar=$1 ;;
*.properties) file=$1
esac

case $2 in
*\.jar) jar=$2 ;;
*.properties) file=$2
esac

if [[ "$jar" = "" ]] 
then
    jar="$scriptdir/@CUSTOM_JAR_NAME@"
fi

if [[ "$file" = "" && "$jar" != "" ]]
then
    file=`java -Done-jar.main.class="org.solrmarc.tools.PropertyFileFetcher" -jar "$jar" | egrep "solr.indexer.properties" | sed -e's/.*= *//'`
fi

# jar uf "$jar" $file
java -Done-jar.main.class="org.solrmarc.tools.PropertyFileFetcher" -jar "$jar" JarUtils.jar $scriptdir
java -classpath $scriptdir/JarUtils.jar JarUpdater "$jar" $file > /dev/null
rm -f $scriptdir/JarUtils.jar

echo "Property file: $file  updated into jar file."
