#! /bin/bash
# updatesolrserver
# send an update message to a running solr server, 
# $Id: updatesolrserver

E_BADARGS=65

scriptdir=$( (cd -P $(dirname $0) && pwd) )

java @MEM_ARGS@ -Done-jar.main.class="org.solrmarc.tools.SolrUpdate" -jar $scriptdir/@CUSTOM_JAR_NAME@ $1 

exit 0

