#!/bin/bash
JAVA_HOME=/usr/java/latest
export JAVA_HOME
fpath=$1
fpattern=$2
scriptdir=$( (cd -P $(dirname $0) && pwd) )

for file in `find $fpath -name '*.mrc' -print | sort | egrep "$fpattern"`
    do
        f1=${file%.*}
        f2=${f1##*/}
        output=/usr/local/projects/marc/results/results_sas_$f2
        del="$f1".del
        if [ -a "$del" ]
            then f3=$del
            else  del=""
        fi
        echo $file
        $scriptdir/indexfile blacklight_sas_config.properties $file $del > $output 2>&1
        if [ "$?" -eq 1 ]
        then
           break  # Skip entire rest of loop.
        fi
    done
