#!/bin/sh
JAVA_HOME=/usr/java/latest
export JAVA_HOME
if [ $# -eq 0 ]
  then
    echo "    Usage: `basename $0` /directory/containing/marc/files  'MarcFieldSubfield/string to look for' 'regexForFileNameMacthing' "
    echo "  example: `basename $0` /directory/containing/marc/files  '999m/AT-SEA' 'regexForFileNameMacthing' "
    echo "  example: `basename $0` /directory/containing/marc/files  '856u' 'regexForFileNameMacthing' "
    echo "  example: `basename $0` /directory/containing/marc/files  'XXXa/string'  "
    echo "  example: `basename $0` /directory/containing/marc/files  'XXXa' 'regexForFileNameMacthing' "
    exit $E_BADARGS
fi

scriptdir=$( (cd -P $(dirname $0) && pwd) )

case $1 in
*config.properties) config=$1 ; shift;;
esac


fpath=$1
marcpattern=$2
fpattern=$3
marcpattern2=`echo $2 | sed -e 's:/:_:g'`

for file in `find $fpath -name '*.mrc' -print | sort | egrep "$fpattern"`
    do
        f1=${file%.*}
        f2=${f1##*/}
        output=/usr/local/projects/marc/results/results_${marcpattern2}_${f2}
        del="$f1".del
        if [ -a "$del" ]
            then f3=$del
            else  del=""
        fi
        echo $file
        cat $file | $scriptdir/filterrecords $marcpattern | $scriptdir/indexfile $del > $output 2>&1
        if [ "$?" -eq 1 ]
        then
           break  # Skip entire rest of loop.
        fi
    done