#!/bin/sh
JAVA_HOME=/usr/java/latest
export JAVA_HOME
if [ $# -eq 0 ]
  then
    echo "    Usage: `basename $0` [config.properties] /directory/containing/marc/files  'regexForFileNameMacthing' "
    echo "      or : `basename $0` [config.properties] /directory/containing/marc/files "
    exit $E_BADARGS
fi

scriptdir=$( (cd -P $(dirname $0) && pwd) )
config=""
case $1 in
*config.properties) config=$1 ; shift;;
esac

fpath=$1
fpattern=$2

for file in `find $fpath -name '*.mrc' -print | sort | egrep "$fpattern"`
    do
        f1=${file%.*}
        f2=${f1##*/}
        output=/usr/local/projects/marc/results/results_${config}_${f2}
        del="$f1".del
        if [ -a "$del" ]
            then f3=$del
            else  del=""
        fi
        echo $file
        $scriptdir/indexfile $config $file $del > $output 2>&1
        if [ "$?" -eq 1 ]
        then
           break  # Skip entire rest of loop.
        fi
    done
