#!/bin/sh
JAVA_HOME=/usr/local/java/
export JAVA_HOME
fpath=$1
fpattern=$2

for file in `find $fpath -name '*.mrc' -print | sort | egrep "$pattern"`
    do
        f1=${file##*/}
        f2=${f1%.*}
        output=./results/results_$f2
        /usr/local/java/bin/java -Xmx1024M -Dmarc.path="$file" -Dsolr.optimize_at_end="false" -Dsolr.hosturl="" -jar dist/MarcImporter.jar import.properties > $output 2>&1
        if [ "$?" -eq 1 ]
        then
           break  # Skip entire rest of loop.
        fi
    done

